import type { Metadata } from "next";
import { Inter,Roboto } from "next/font/google";
import "./globals.css";
// import "@/externaljsfile/main.550ac09d"
// import "@/externaljsfile/336.d8b87783.chunk"
// import "@/externaljsfile/614.b5584f3f.chunk"
// import "@/externaljsfile/Edit.90164fab.chunk"


const inter = Roboto({subsets:["cyrillic"],weight:"400"});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen`}>{children}</body>
    </html>
  );
}
