// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
import { ScrollArea } from "@/components/ui/scroll-area";
import Header from "./(components)/Header";
import Navbar from "./(components)/Navbar";
import LinkComponent from "./(components)/LinkComponent";
import MobileNav from "./(components)/MobileNav";
// import "@/externaljsfile/main.550ac09d"
// import "@/externaljsfile/336.d8b87783.chunk"
// import "@/externaljsfile/614.b5584f3f.chunk"
// import "@/externaljsfile/Edit.90164fab.chunk"


// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <div className=" flex  fixed h-full w-full">
    <ScrollArea>
    <MobileNav/>
    <div className=" hidden md:block">
    <Navbar/>
    </div>
    
    </ScrollArea>
    <div className=" flex-1 bg-[#f7f7f8]   ">
        <Header/>
        <ScrollArea className=" overflow-y-auto h-full ">
        {children}
        </ScrollArea>
    </div>
   </div>
  );
}
